#!/bin/bash
# clone/update Github Repo 

printf "        \033[34m clone/update Github Repo Tool \033[0m \n"

if [[ -d GithubRepo ]];then
    echo -e "\033[35m即将下载已配置的Repo到本地。\033[0m"
else
    
    echo -e "\033[36m\n首次检出GitHub Repo，已为您自动处理子组件仓库主目录. \033[0m"
    echo -e "\033[35m请输入您的邮箱信息 \033[0m"
    
    read coding_code_email   

    # coding_code_name=${coding_code_email%@*} >/dev/null 2>&1
    coding_code_name='DevDragonLi' >/dev/null 2>&1
    echo -e "\033[36m您输入的GitHub Repo配置信息如下⬇️\n\n\033[34mEmail :\033[32m${coding_code_email}\n\033[34mAuthor:\033[32m${coding_code_name}\033[0m"
    mkdir GithubRepo
fi 

echo -e "\033[35m\nBegain clone/update GitHub Repo ! Please Waiting ☕️\033[0m"

if [[ -d .config ]];then
    echo 
else
   	echo -e "\033[31m无法读取依赖配置信息，同步终止！\033[0m" 
    exit 0  
fi

coding_ssh_url=`head -n +1 .config/codingrooturl` 

cat ./.config/repoNameList | while read pod_name ;do

    if [[ -d GithubRepo/${pod_name} ]]; then

        (cd GithubRepo/${pod_name} && git stash  >/dev/null 2>&1 && git pull --rebase >/dev/null 2>&1 && git stash pop  >/dev/null 2>&1)   
       
        cd GithubRepo/${pod_name}
        # (cp -f  ../../subPodconfig/pre-commit .git/hooks/pre-commit)
        
        this_pod_git_name=`git config --local user.name` 

        if [ -n "$this_pod_git_name" ];then
            echo -e "\033[36mHello ${this_pod_git_name} : \033[34m${pod_name}Repo已同步完成！！！\033[0m"
        else
            #未配置
            echo -e "\033[34m   ${pod_name}Repo已同步完成！！！\n\033[0m"
            echo -e "\033[31m${pod_name} Git Info unSettings，Please following below cmd run by Youself！\n 1.config user.name xxx\n 2.config user.email xxx\033[0m"
        fi

        cd ../../
    else
        (cd GithubRepo && git clone ${coding_ssh_url}${pod_name}  >/dev/null 2>&1 && cd ${pod_name} && git config user.email $coding_code_email && git config user.name $coding_code_name )
        
        echo -e "\033[35m🚴本地缺失的${pod_name}Repo,已下载完毕。\033[0m"
    fi 

done

